drop table `orders` if exists;
create table `orders` (id int generated by default as identity, created_at timestamp, primary key (id));
drop table `order_line` if exists;
create table `order_line` (id int generated by default as identity, order_id int, product_id bigint, quantity int, price decimal, primary key (id));
alter table order_line add foreign key  ( order_id ) references  `orders`(id);