eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOST:eureka-server}:${DISCOVERY_SERVER_PORT:8761}/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5

spring:
   zipkin:
      baseUrl: http://${ZIPKIN_SERVER_HOST:zipkin-dashboard}:${ZIPKIN_SERVER_PORT:9411}
   sleuth:
     sampler:
       percentage: 1.0
       
# disable actuator security
management:
  security:
    enabled: false